// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLrMo_1ScivMpwj3nHPJ0gio6OaG4_IbQ',
    appId: '1:890838174372:web:19edd5beb0c6b34c46b431',
    messagingSenderId: '890838174372',
    projectId: 'tinble',
    authDomain: 'tinble.firebaseapp.com',
    storageBucket: 'tinble.appspot.com',
    measurementId: 'G-8XCN7JGXJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACRRXlDNP3CSQ0V3b55w7Vk1HLeOcREKA',
    appId: '1:890838174372:android:6f82aaf63c8a07ec46b431',
    messagingSenderId: '890838174372',
    projectId: 'tinble',
    storageBucket: 'tinble.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3V5zO1vLgJpRGYfUNhLly3DDUDhKPd64',
    appId: '1:890838174372:ios:a3a7bc81e017aba946b431',
    messagingSenderId: '890838174372',
    projectId: 'tinble',
    storageBucket: 'tinble.appspot.com',
    iosClientId: '890838174372-kgivr6g5eo386aindjiuguc2rjltkq20.apps.googleusercontent.com',
    iosBundleId: 'com',
  );
}
